name: Deploy Backend to ECS

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR Public
        run: |
          aws ecr-public get-login-password \
            --region us-east-1 | docker login \
            --username AWS \
            --password-stdin public.ecr.aws

      - name: Build & Push Docker Image
        run: |
          cd backend
          docker build -t public.ecr.aws/g9k8y8q1/mini-gallery-backend:latest .
          docker push public.ecr.aws/g9k8y8q1/mini-gallery-backend:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: backend/task-def.json
          service: mini-gallery-task
          cluster: mini-gallery-cluster
          wait-for-service-stability: true
        env:
          AWS_REGION: ap-southeast-1
          AWS_DEFAULT_REGION: ap-southeast-1
